PrimeCollaborationManager/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PrimeCollaborationManager.Helpers;
using PrimeCollaborationManager.Models;
using PrimeCollaborationManager.Models.Requests;
using PrimeCollaborationManager.Services;
using Serilog;
using Serilog.Core;
using Studio.Api.Client;
using Studio.Api.Model.Logs;

namespace PrimeCollaborationManager.Controllers
{
    [Authorize]
    public class ProjectsController : Controller
    {
        protected StudioApplicationConfig Config { get; set; }
        protected StudioClient Client { get; set; }
        protected UserLog UserLog { get; set; }
        protected ICollaborationService CollaborationService { get; set; }
        public ProjectsController(StudioApplicationConfig config)
        {
            Config = config;
        }

        protected virtual async Task InitClient()
        {
            UserLog = UserHelper.GetCurrentUser(HttpContext);
            Client = new StudioClient(Config, UserLog, Log.Logger);
            var token = await HttpContext.GetTokenAsync("access_token");
            Client.SetAuthHeader(token);
            CollaborationService = new ProjectsCollabService(Client, Config.ApiResultPageSize);
        }

        public async Task<IActionResult> Index(int page = 1)
        {
            try
            {
                await InitClient();
                var projects = await CollaborationService.GetListAsync(page);
                return View(projects);
            }
            catch (StudioApiException e)
            {
                return HandleError(e);
            }
        }

        public async Task<IActionResult> Details(string collabId)
        {
            try
            {
                await InitClient();
                var project = await CollaborationService.GetDetailsAsync(collabId);
                var model = new CollaborationDetails { Collab = project };
                return View(model);
            }
            catch (StudioApiException e)
            {
                return HandleError(e);
            }
        }

        #region permissions
        [HttpPost]
        public async Task<IActionResult> UpdateAccess(string collabId, bool newRestrictedStatus)
        {
            try
            {
                await InitClient();
                await CollaborationService.UpdateCollaborationAccessAsync(collabId, newRestrictedStatus);

                return RedirectToAction("Details", new Dictionary<string, string> { { "collabId", collabId } });
            }
            catch (StudioApiException e)
            {
                return HandleError(e);
            }
        }

        public async Task<IActionResult> PermissionDetails(string collabId)
        {
            try
            {
                await InitClient();
                var detail =  CollaborationService.GetDetailsAsync(collabId);
                var perms =  CollaborationService.GetPermissionsAsync(collabId);
                await Task.WhenAll(detail, perms);
                var allPerms = CollaborationService.GetPermissionTypes();
                var foundTypes = perms.Result.Select(p => p.Type).ToList();
                foreach (var perm in allPerms)
                {
                    if (!foundTypes.Contains(perm))
                        perms.Result.Add(new Studio.Api.Model.Permissions.Permission(perm, (bool?)null));
                }
                var model = new CollaborationDetails { Collab = detail.Result, Permissions = perms.Result };
                return View(model);
            }
            catch (StudioApiException e)
            {
                return HandleError(e);
            }
        }

        public async Task<IActionResult> UpdatePermissions([Bind] UpdateCollabPermissionsRequest request)
        {
            try
            {
                if (request == null)
                    return BadRequest();

                await InitClient();
                await CollaborationService.SetPermissionsAsync(request);
                return RedirectToAction("PermissionDetails", new Dictionary<string, string> { { "collabId", request.CollabId } });
            }
            catch (StudioApiException e)
            {
                return HandleError(e);
            }
        }
        #endregion

        #region Users
        public async Task<IActionResult> UserList(string collabId, int page = 1)
        {
            try
            {
                await InitClient();
                var detail = CollaborationService.GetDetailsAsync(collabId);
                var users = CollaborationService.GetUsersAsync(collabId, page);
                await Task.WhenAll(detail, users);
                var model = new CollaborationDetails { Collab = detail.Result, Users = users.Result };
                return View(model);
            }
            catch (StudioApiException e)
            {
                return HandleError(e);
            }
        }

        [HttpPost]
        public async Task<IActionResult> UpdateUserPermission(string collabId, int page, int user, bool allow)
        {
            try
            {
                await InitClient();
                await CollaborationService.UpdateUserRestrictedStatusAsync(collabId, user, allow ? "Allow" : "Deny");
                return RedirectToAction("UserList", new Dictionary<string, string> { { "collabId", collabId }, { "page", $"{page}" } });
            }
            catch (StudioApiException e)
            {
                return HandleError(e);
            }
        }
        #endregion

        #region CreateProject
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            try
            {
                await InitClient();
                var model = new CreateCollaboration()
                {
                    Restricted = true,
                    InitialPermissionTypes = CollaborationService.GetPermissionTypes()
                };
                return View(model);
            }
            catch (StudioApiException e)
            {
                return HandleError(e);
            }
        }

        [HttpPost]
        public async Task<IActionResult> CreateSubmit(IFormCollection form)
        {
            try
            {
                await InitClient();
                var id = await CollaborationService.CreateAsync(form);
                return RedirectToAction("Details", new { collabId = id });
            }
            catch (StudioApiException e)
            {
                return HandleError(e);
            }
        }
        #endregion

        protected IActionResult HandleError(StudioApiException e)
        {
            Log.Logger.Error("Error encountered; User: {@User}; Exception: {Exception}", UserLog, e);
            return View("Error", new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier, StudioError = e });
        }
    }
}

PrimeCollaborationManager/Controllers/SessionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PrimeCollaborationManager.Helpers;
using PrimeCollaborationManager.Models;
using PrimeCollaborationManager.Services;
using Serilog;
using Studio.Api.Client;

namespace PrimeCollaborationManager.Controllers
{
    public class SessionsController : ProjectsController
    {
        public SessionsController(StudioApplicationConfig config)
            :base(config)
        {
        }

        protected override async Task InitClient()
        {
            UserLog = UserHelper.GetCurrentUser(HttpContext);
            Client = new StudioClient(Config, UserLog, Log.Logger);
            var token = await HttpContext.GetTokenAsync("access_token");
            Client.SetAuthHeader(token);
            CollaborationService = new SessionsCollabService(Client, Config.ApiResultPageSize);
        }

        #region Activity
        public async Task<IActionResult> Activity(string collabId, int page = 1)
        {
            try
            {
                await InitClient();
                var detail = CollaborationService.GetDetailsAsync(collabId);
                var ars = CollaborationService.GetActivity(collabId, page);
                await Task.WhenAll(detail, ars);
                var cd = new CollaborationDetails { Collab = detail.Result, IsSessionActivityPage = true};
                var model = new SessionActivity { Activities = ars.Result, CollaborationDetails = cd };
                return View(model);
            }
            catch (StudioApiException e)
            {
                return HandleError(e);
            }
        }
        #endregion
    }
}

PrimeCollaborationManager/Views/Shared/CollabNavbar.cshtml
@model CollaborationDetails
    <nav class="navbar navbar-dark navbar-expand-lg bg-dark">
        <div class="navbar-brand">Studio @Html.DisplayFor(model => model.Collab.Type) @Html.DisplayFor(model => model.Collab.Id) : @Html.DisplayFor(model => model.Collab.Name)</div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                @{
                    var detailParam = new Dictionary<string, string> { { "collabId", Model.Collab.Id } };
                    var generalClass = "nav-item active";
                    var permClass = "nav-item";
                    var userClass = "nav-item";
                    var activityClass = "nav-item";
                    if (Model.Permissions != null)
                    {
                        generalClass = "nav-item";
                        permClass = "nav-item active";
                    }
                    if (Model.Users != null)
                    {
                        generalClass = "nav-item";
                        userClass = "nav-item active";
                    }
                    if (Model.IsSessionActivityPage)
                    {
                        generalClass = "nav-item";
                        activityClass = "nav-item active";
                    }
                }
                <li class="@generalClass">
                    <a class="nav-link" asp-action="Details" asp-all-route-data="detailParam">General </a>
                </li>
                <li class="@permClass">
                    <a class="nav-link" asp-action="PermissionDetails" asp-all-route-data="detailParam">Permissions </a>
                </li>
                <li class="@userClass">
                    <a class="nav-link" asp-action="UserList" asp-all-route-data="detailParam">Users </a>
                </li>
                @if (Model.Collab.Type == "Session")
                {
                <li class="@activityClass">
                    <a class="nav-link" asp-action="Activity" asp-all-route-data="detailParam">Activity </a>
                </li>
                }
            </ul>
        </div>
    </nav>

PrimeCollaborationManager/Views/Shared/CollabPermissionList.cshtml
@model CollaborationDetails
@using PrimeCollaborationManager.Helpers

<partial name="CollabNavbar" model="@Model" />
<p>These permissions will be applied to users who have access to this Studio @Model.Collab.Type, but do not have Group or User permissions set.</p>
<form asp-action="UpdatePermissions" method="post">
    <input type="hidden" name="CollabID" value="@Model.Collab.Id" />
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>
                    Permission Type
                </th>
                <th>
                    Current Setting
                </th>
                <th>
                    New Setting
                </th>
            </tr>
        </thead>
        <tbody>
            @{
                var options = new string[] { "Allow", "Deny", "Default" };
            }
            @foreach (var item in Model.Permissions)
            {
                <tr>
                    <td>
                        @PermissionTextHelper.GetPermissionDisplayName(item.Type)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Allow)
                    </td>
                    <td>
                        <select class="custom-select" data-style="btn-info" name="@item.Type" id="@item.Type">
                            <option selected="selected">
                                -
                            </option>
                            @foreach (var opt in options)
                            {
                                if (item.Allow != opt)
                                {
                                    <option>
                                        @opt
                                    </option>
                                }
                            }
                        </select>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <input type="submit" value="Update Permissions" class="btn btn-primary btn-block" />
</form>
<div><a asp-action="Index">Back to Studio @Model.Collab.Type List</a></div>

PrimeCollaborationManager/Views/Shared/CollabTable.cshtml
@model CollaborationList

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>
                #
            </th>
            <th>
                ID
            </th>
            <th>
                Name
            </th>
            <th>
                Restricted
            </th>
            <th>
                Owner
            </th>
            @if (Model.ShowTimes)
            {
                <th>
                    Created at
                </th>
            }
            @if (Model.ShowStatus)
            {
                <th>
                    Status
                </th>
            }
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            int collabNum = 1 + (Model.Collaborations.CurrentPage - 1) * Model.Collaborations.ItemsPerPage;
        }
        @foreach (var item in Model.Collaborations.Items)
        {
            <tr>
                <td>
                    @collabNum
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Restricted)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Owner)
                </td>
                @if (Model.ShowTimes)
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.Created)
                    </td>
                }
                @if (Model.ShowStatus)
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                }
                <td>
                    @Html.ActionLink("Details", "Details", new { collabId = item.Id })
                </td>
            </tr>
            collabNum = collabNum + 1;
        }
    </tbody>
</table>


PrimeCollaborationManager/Views/Shared/CollabUserList.cshtml
@model CollaborationDetails

<partial name="CollabNavbar" model="@Model" />
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>
                #
            </th>
            <th>
                Email
            </th>
            <th>
                Name
            </th>
            <th>
                Access
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            int collabNum = 1 + (Model.Users.CurrentPage - 1) * Model.Users.ItemsPerPage;
        }
        @foreach (var item in Model.Users.Items)
        {
            <tr>
                <td>
                    @collabNum
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RestrictedStatus)
                </td>
                <td>
                    @if (item.RestrictedStatus == "Allow")
                    {
                        var routeParams = new Dictionary<string, string> { { "collabId", Model.Collab.Id }, { "page", Model.Users.CurrentPage.ToString() }, { "user", item.Id.ToString() }, { "allow", "false" } };
                        <form asp-action="UpdateUserPermission" asp-all-route-data="routeParams" method="post"><input type="submit" class="btn btn-outline-danger" value="Deny" /></form>
                    }
                    else
                    {
                        var routeParams = new Dictionary<string, string> { { "collabId", Model.Collab.Id }, { "page", Model.Users.CurrentPage.ToString() }, { "user", item.Id.ToString() }, { "allow", "true" } };
                        <form asp-action="UpdateUserPermission" asp-all-route-data="routeParams" method="post"><input type="submit" class="btn btn-outline-primary" value="Allow" /></form>
                    }
                </td>
            </tr>
            collabNum = collabNum + 1;
        }
    </tbody>
</table>
@{
    var pagedResultDisplay = Model.Users.GetModelForDisplay("UserList");
    pagedResultDisplay.ActionParams["collabId"] = Model.Collab.Id;
}
<partial name="PagedResultNavBar" model="pagedResultDisplay" />
<div>    <a asp-action="Index">Back to Studio @Model.Collab.Type List</a></div>

PrimeCollaborationManager/Views/Shared/PagedResultNavbar.cshtml
@model PagedResultDisplay
@if (Model.TotalItems > Model.ItemsPerPage)
{
    <nav aria-label="Page navigation">
        <ul class="pagination">
            <li class="page-item disabled"><a class="page-link" href="#" >Page:</a></li>
            @{
                Model.ActionParams["page"] = "1";
            }
            @for (int p = 1; p * Model.ItemsPerPage < Model.TotalItems + Model.ItemsPerPage; p++)
            {
                Model.ActionParams["page"] = p.ToString();
                if (p == Model.CurrentPage)
                {
                    <li class="page-item active">
                        <a class="page-link" asp-action="@Model.ControllerAction" asp-all-route-data="@Model.ActionParams">@p </a>
                    </li>
                }
                else
                {
                    <li class="page-item">
                        <a class="page-link" asp-action="@Model.ControllerAction" asp-all-route-data="@Model.ActionParams">@p </a>
                    </li>
                }
            }
        </ul>
    </nav>
}

PrimeCollaborationManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @Resources.AppName</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@Resources.AppName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (User != null && User.Identity.IsAuthenticated && !String.IsNullOrEmpty(User.Identity.Name))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Projects" asp-action="Index">Studio Projects</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Sessions" asp-action="Index">Studio Sessions</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        @if (ViewData.ModelState.ErrorCount > 0) // error logic here 
        { 
        <div class="alert alert-danger" role="alert">
            Errors present in modelstate
        </div>
        }
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.UtcNow.Year - @Resources.AppName - <a asp-area="" asp-controller="Home" asp-action="Help">Help</a> - <a asp-area="" asp-controller="Home" asp-action="Features">Features</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>